pipeline {
    agent any

    stages {
        stage('docker build') {
            steps {
                script {
                    bat "docker build -f 02-primer-pipeline/Dockerfile -t elimasrojas/homer_page:1.0.0-${BUILD_ID} 02-primer-pipeline"
                }
            }
        }
        stage('docker push') {
            steps {
                script {
					bat "docker login -u elimasrojas -p Colombia0210"
                    bat "docker push elimasrojas/homer_page:1.0.0-${BUILD_ID}"
                }
            }
        }
    }
}